### ISSUE TITLE
Create website project

### ISSUE THREAD

**Issue by jehrhardt** [jehrhardt/contenteditable-website#2]
### Problem
We need a simple [Fresh](https://fresh.deno.dev) project, hosted on Denoland, to try contenteditable out.

### Tasks

- [x] Create Fresh project
- [x] Setup CI build
- [x] Host on Denoland
- [x] Configure contenteditable.dev to serve it
- [x] Ensure HTTPS and IPv6

**Comment by jehrhardt** [comment]
Everything is setup on https://contenteditable.dev ✅
